export const languageToSymbolMap = {
    "python": "Py",
    "javascript": "JS",
    "typescript": "TS",
    "java": "java",
    "csharp": "C#",
    "go": "GO",
    "rust": "Rust",
    "php": "PHP",
    "ruby": "Ruby",
    "swift": "Swift",
    "kotlin": "Kotlin",
    "scala": "Scala",
    "r": "R",
    "matlab": "MATLAB",
    "sql": "SQL",
    "c": "C",
    "cpp": "C++",
    "c++": "C++",
};