// Maps language names to short display symbols used in badges/cards
export const languageToSymbolMap = {
    "python":     "Py",
    "javascript": "JS",
    "typescript": "TS",
    "java":       "Jv",
    "csharp":     "C#",
    "go":         "Go",
    "rust":       "Rs",
    "php":        "PHP",
    "ruby":       "Rb",
    "swift":      "Sw",
    "kotlin":     "Kt",
    "scala":      "Sc",
    "r":          "R",
    "matlab":     "ML",
    "sql":        "SQL",
    "c":          "C",
    "cpp":        "C++",
    "c++":        "C++",
    "html":       "HTML",
    "css":        "CSS",
    "shell":      "SH",
    "bash":       "SH",
    "dart":       "Dt",
    "elixir":     "Ex",
    "haskell":    "Hs",
    "lua":        "Lua",
    "perl":       "Pl",
    "vue":        "Vue",
    "svelte":     "Sv",
};
